# Generated by Django 2.1.3 on 2018-11-27 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0002_auto_20181127_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='genes',
            name='Gname',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
